### ISSUE TITLE
Feature: User can view other user's single profile

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view other user's single profiles
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User are able to view other user's single profiles
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/201986732-f3da2f0d-af17-4dad-9fa2-f4abf6a8021e.png)
![image](https://user-images.githubusercontent.com/109745413/201986762-207f1615-5676-43d3-b375-503d09b0476d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update hash route for app to "user-account"
- [x] Detect a hash change to "user-account" and display the current user's profile
- [x] Add an event listener for detecting when the username is being clicked on when viewing other profiles
- [x] Display a card of their current profile

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
