### ISSUE TITLE
Feature: User can log in

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to create an account and sign in
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be prompted to create an account or sign in 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/109745413/202254472-028c2b45-bf6c-454f-863b-45db39de0058.png)
![image](https://user-images.githubusercontent.com/109745413/202254530-4ea2ba4b-2095-4e79-81ed-741a3882d2a1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include a hashed password column
- [x] Update `data.sql` to include pre-set passowrds

### ☁️ Server Tasks

- [x] Update `server/index.js` to include an authorization middleware
- [x] Update `server/index.js` to handle sign up page 
- [x] Update `server/index.js` to handle sign in page
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update all components to use created tokens
- [x] Update app to route to include sign in and sign up
- [x] Update app to route from sign in to sign up
- [x] Update app to route from sign up to sign in
- [x] Update all components to route to sign up if no user is logged in

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
