### ISSUE TITLE
Feature: User can log out

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log out of the app
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to see a users icon that opens a pop up for the user to log out

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/202512290-10aa51ce-4601-4d74-be27-490d70c54a99.png)
![image](https://user-images.githubusercontent.com/109745413/202512326-fb8075e1-7aa5-4211-a3e0-ee2f58af7cb5.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update account card component to display an users icon
- [x] Add a click event listener to the icon that pops out a sidebar
- [x] Add two buttons to the sidebar
- [x] Add a log out icon
- [x] Change the hash to #log-in when log out icon is clicked
- [x] Delete the user information in local storage

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
