### ISSUE TITLE
Feature: User can view their profile

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their profile they created

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view their profile they created

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/200031240-ce900d0d-7a51-40a4-96d6-3e56aeb08fbb.png)
![image](https://user-images.githubusercontent.com/109745413/200031279-cc5e18fd-ba68-4506-85f5-7dd059f74fcf.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to retrieve get request for username
- [x] Update server to send query for accounts table where the username is the same
- [x] Respond with a an object that has has account information. Ie. username, accountId, mood, and rating
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a view account component to display user name, profile picture, and rating
- [x] Send a get request for the account data
- [x] Create half stars using css
- [x] Create three moods in css based on star rating
- [x] Create a function for generating stars based on rating
- [x] Update the function for changing color based on mood
- [x] Create a context or use props to keep track of username
- [x] Update home component to navigate to view account after account creation
- [x] Set up hash routing to transition from createAccount to viewAccount
- [x] Stored username to local storage once account is created

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
