### ISSUE TITLE
Feature: User can view other user’s profiles

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view other user’s profiles
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view other user’s profiles by selecting the home icon on the top left hand side

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/200031520-59ce17ad-9dbb-4a56-85f0-0c1beb4ba58b.png)
![image](https://user-images.githubusercontent.com/109745413/200031550-c7bdcba0-45a5-4373-b86f-53bd96c42766.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include 2 more profiles

### ☁️ Server Tasks

- [x] Update `server/index.js` to query for all accounts other than the current user
- [x] Return the result as an array of objects
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new component to view other accounts
- [x] Create other account cards for viewing
- [x] fetch all other account data from the current users from the accounts table and store the items in an array
- [x] Set up hash routing for viewing other accounts
- [x] Set up carousel for scrolling through users
- [x] Render only 3 users at a time
- [x] Set up css for smooth transition
- [x] Update view other account component to redirect to current user profile by clicking the smiley face
- [x] Update view profile component to display a home icon that redirects to the view other profile component
- [x] Set up hash changing to "view-other-accounts" when home icon is clicked

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
