### ISSUE TITLE
Feature: User can rate other users profiles

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can rate other users profiles

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can have a option of select a rating for the profile they are viewing and press check for committing their rating or x mark for not rating
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/200031838-99fe1253-861e-436b-9bc2-0fa9ebbb000d.png)
![image](https://user-images.githubusercontent.com/109745413/200031864-73c0b0fa-c7fd-4ffb-bad1-d35ca0117731.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include rating information

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a post request to ratings tables that stores username of who rated the user, who it was rated by, and the rating
- [x] Update the current rating of the user on the accounts table using an sql update statement
- [x] Take the average of the rating's table by accountId and save the new value as the new currentRating value
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update account-card component to contain two buttons, for accept and one for decline
- [x] Update the account card component to display an updated star system when hovered over
- [x] Set up event handler for detecting the id for the star when clicked
- [x] Update the rating state with the id of the item when clicked
- [x] Detect the id of the star that is hovered
- [x] Update component to send a post request to the server when accept button is clicked
- [x] Update component to hide the star system to hide after the accept button is clicked and replace it with the account stars rating 
- [x] Update right and left chevrons to display the star rating system when clicked

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
