### ISSUE TITLE
Feature: User can leave a comment

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can leave a comment
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can leave a comment for a user by selecting the message icon. They user card will flip and the user can leave a comment. Once they are ready to move on from the user, they can select the check mark
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/109745413/200032285-c10a3008-0c17-44ed-a3ac-5beffc39b5db.png)
![image](https://user-images.githubusercontent.com/109745413/200032318-b336561f-0e90-40d5-a646-05ccf180cea8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to post new comment into comments table
- [x] Create a post route that adds whoCommented, commentedWho, and comment
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update account card component to include a comment icon
- [x] Add a click event listener for the comment icon
- [x] Update account card component with click event listener to flip to the comment card
- [x] Create a div to store the form
- [x] Create a form for receiving comments
- [x] Add in a text area inside the form
- [x] Clear form once comment is submitted when the green check mark is clicked

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
