### ISSUE TITLE
Feature: User can view their comments

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their comments
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view the comments left on their profile. User can navigate to their home profile by selecting the happy face at the top of the screen. Then, they can select the message icon and view their comments left by other users
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/200032663-34a93bc7-115d-4f7a-b115-7446363f94ca.png)
![image](https://user-images.githubusercontent.com/109745413/200032688-33041468-c246-457e-b6f4-afc83e894a13.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a get request for all comments involving an accountId
- [x] Return commenter, comment, and commenter image url
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update view-account component to flip to comment card when comment icon is clicked
- [x] Send a fetch request when comment icon is clicked 
- [x] Fetch the user's, comment, commenterId and commenter image url
- [x] Store all comments and commenter image url as an object in a comment array as a state
- [x] Create a card component to display commenter image and comment
- [x] Update the card component to take in props of image url and comment
- [x] Set up scrolling feature of form comments that exceed the length of the card 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
