### ISSUE TITLE
Feature: User can follow a profile

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can follow a profile
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can add profiles to their follower list. They can press the star button to add the user to their follower list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/200032870-a5bb3ae3-8169-4c83-8a67-8bc86d6d923d.png)
![image](https://user-images.githubusercontent.com/109745413/200032900-5df6f7ca-cdaa-4dc5-81b7-4bf634a42cdb.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a post path for adding profiles to followers list
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update account card component to include a button for following
- [x] Add an event listener to the button for click events
- [x] Update the name, rating, and comment icon color to gold
- [x] Send a fetch request to store the information

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
