### ISSUE TITLE
Feature: User can view their followed profiles

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their followed profiles
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can select the group icon on the top right of the app and view a list of their followers

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/109745413/202817358-fe5e8296-3a31-407b-b9c9-70d600996bad.png)
![image](https://user-images.githubusercontent.com/109745413/202817373-8d825d3b-ba9e-4d13-989a-f84bac2e9131.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Create a component to display a list of followers
- [ ] Update the component to navigate to the list of followers
- [ ] Update the sidebar component to detect a new user is added as a follower

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
